name: Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at every 12AM UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: README
    runs-on: windows-latest
    steps:
      - uses: wenwed/README@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
